Update README with CI and Trello info
IIS-ZPI/ZPI2022_IO3_Tech_Titans pull request #30
Opened 2023-04-04 20:39 UTC by kasia251011

2023-04-04 21:58 UTC, cpprian commented on README.md
> +Purpose of this project is to display statistics of excange rates.
small typo

2023-04-04 21:59 UTC, cpprian approved these changes
There is a small typo, rest lgfm

2023-04-05 06:14 UTC, Ewangelina requested changes
As it is a public repository, are we sure we want to paste an invite link to trello here?

2023-04-05 06:14 UTC, Ewangelina commented on README.md
> +CI is achieved by GitHub Actions, and pipeline provide file `node.yaml` which build project on node 18, and runs tests.
I find this sentence hard to understand.
"CI is achieved by GitHub Actions, and the pipeline is provided by the file `node.yaml` which builds the project on node 18, and runs tests."
Or
"CI is achieved by GitHub Actions, and the pipeline provides the file `node.yaml` which builds the project on node 18, and runs tests."

2023-04-05 06:50 UTC, kasia251011 commented on README.md
> +CI is achieved by GitHub Actions, and pipeline provide file `node.yaml` which build project on node 18, and runs tests.
Generally I meant:
`CI is achieved by GitHub Actions, and file node.yaml provides pipeline which builds the project on node 18, and runs tests.`

Would it be okey?

2023-04-05 06:55 UTC, kasia251011 commented
> As it is a public repository, are we sure we want to paste an invite link to Trello here?

I have blocked option that shares link to Trello with only view access. 😒 I have to link the backlog (requirement), so I think we have to leave it as it is, or do you have another idea?

2023-04-05 07:06 UTC, Ewangelina approved these changes

2023-04-05 08:21 UTC, merged