prep repo for testing in jestjs
IIS-ZPI/ZPI2022_IO3_Tech_Titans pull request #38
Opened 2023-04-11 22:19 UTC by cpprian

2023-04-11 22:30 UTC, kasia251011 commented on package.json
> +    "coverage": "jest --coverage --watchAll",
are you sure that it works?

2023-04-11 22:33 UTC, kasia251011 commented on package.json
> +    }
As I know, app created with create-react-app dont need special configuration for jest:
https://create-react-app.dev/docs/running-tests/#coverage-reporting

If you wanted to override deafult configuration, please describe what you wanted to achieve.

2023-04-11 22:33 UTC, kasia251011 requested changes
.

2023-04-12 10:36 UTC, cpprian commented on package.json
> +    "coverage": "jest --coverage --watchAll",
yes, but we can stay with react-scripts cli

2023-04-12 10:37 UTC, cpprian commented on package.json
> +    }
collectCoverageFrom -> We want to test only feature components, not configurations or types
coverageThreshold -> It enables you to define minimum acceptable coverage levels for different types of code
preset -> Helps you define js syntax, for react-scripts doesn't work

2023-04-12 10:48 UTC, closed without merging