Szymon statistics unit tests
IIS-ZPI/ZPI2022_IO3_Tech_Titans pull request #40
Opened 2023-04-12 19:21 UTC by SzymonB5

2023-04-12 19:53 UTC, kasia251011 commented on package.json
> +    "@babel/preset-typescript": "^7.21.4",
You dont have to install anything, this template from crate-react-app is already prepared for jest.

2023-04-12 19:53 UTC, kasia251011 commented on package.json
> +    "jest": "^27.5.1",
You dont have to install anything, this template from crate-react-app is already prepared for jest.

2023-04-12 19:53 UTC, kasia251011 commented on src/utilities/BasicStatisticsFunctions.test.tsx
> +import {describe, expect, test} from '@jest/globals';
This import is uneccesary

2023-04-12 19:56 UTC, kasia251011 commented on {
unused file.

2023-04-12 19:58 UTC, kasia251011 requested changes
Tests are fine :) Just repair build problem, and delete unnecessary libraries.

2023-04-13 10:53 UTC, kasia251011 approved these changes

2023-04-13 10:59 UTC, cpprian approved these changes

2023-04-13 11:01 UTC, merged