test rendering a plain table
IIS-ZPI/ZPI2022_IO3_Tech_Titans pull request #41
Opened 2023-04-13 20:20 UTC by cpprian

2023-04-17 13:07 UTC, kasia251011 commented on src/components/BasicStats/BasicStatsTable/index.spec.tsx
> +        <RouterProvider router={router} />
Render directly component that you test.

2023-04-17 13:08 UTC, kasia251011 commented on src/components/BasicStats/BasicStatsTable/index.spec.tsx
> +        <RouterProvider router={router} />
Same as above

2023-04-17 13:19 UTC, kasia251011 commented on src/components/BasicStats/BasicStatsTable/index_mock.spec.tsx
For me this file is totally useless. Or I need explanation what is going on here.

2023-04-17 13:19 UTC, kasia251011 commented on src/components/BasicStats/BasicStatsTable/index.spec.tsx
Add test which will check if data returned form redux hooks.
https://redux.js.org/usage/writing-tests#ui-and-network-testing-tools

I know it can be a little bit overwhelming, and too much information but it is properly way to test components connected to redux. If you need me to give you a little brief about what is redux, and how we are using it in our project just let me know on discord.

If you think that you dont have enought time for that, you can ask for help other teammates.

2023-04-17 13:20 UTC, kasia251011 requested changes
File name for test components should be as I said before: ComponentName.spec.tsx

2023-04-19 17:26 UTC, kasia251011 commented on src/components/BasicStats/BasicStatsTable/BasicStatsTable.spec.tsx
> +  render(<BasicStatsTable />, container);
Why did you create div element?

2023-04-19 17:27 UTC, cpprian commented on src/components/BasicStats/BasicStatsTable/BasicStatsTable.spec.tsx
> +  render(<BasicStatsTable />, container);
<img width="679" alt="Screenshot 2023-04-19 at 19 27 24" src="https://user-images.githubusercontent.com/46838495/233153425-7fe64c8d-0a53-455c-971e-23a8929f55d9.png">

2023-04-19 17:28 UTC, kasia251011 commented on src/components/BasicStats/BasicStatsTable/BasicStatsTable.spec.tsx
> +  const renderedValue = [
What are rendered values?

2023-04-19 17:29 UTC, cpprian commented on src/components/BasicStats/BasicStatsTable/BasicStatsTable.spec.tsx
> +  render(<BasicStatsTable />, container);
This component should be inside sth, the test does not compile without this.

2023-04-19 17:30 UTC, kasia251011 commented on src/components/BasicStats/BasicStatsTable/BasicStatsTable.spec.tsx
> +  }
Cant you just use a table tag to reach rendered table?

2023-04-19 17:31 UTC, kasia251011 reviewed
Just few questions about idea of the test

2023-04-19 17:34 UTC, cpprian commented on src/components/BasicStats/BasicStatsTable/BasicStatsTable.spec.tsx
> +  }
this could be done like this, I will handle it

2023-04-19 21:13 UTC, kasia251011 approved these changes

2023-04-19 21:13 UTC, merged